context:
  version: "7.3.2"

package:
  name: libzeep
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/zeep/archive/v${{ version }}.tar.gz
  sha256: bf679253623710f3f383ec3355968a68672d1ccb96130cb8c0214475561cfd55
build:
  number: 3
  script:
    - if: unix
      then: |
        set -exo pipefail
        export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
        cmake -S . -B build ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON -DZEEP_USE_BOOST_ASIO=OFF
        cmake --build build --parallel ${CPU_COUNT}
        if [[ "${target_platform}" == "linux-aarch64" || "${target_platform}" == "linux-ppc64le" ]]; then
          ctest -V --test-dir build -E "(http-test|daemon-test)"
        fi
        cmake --install build
    - if: win
      then: |
        @echo on
        cmake -S . -B build %CMAKE_ARGS% -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DBUILD_SHARED_LIBS=ON -DZEEP_USE_BOOST_ASIO=OFF
        if errorlevel 1 exit 1
        cmake --build build --config Release --parallel %CPU_COUNT%
        if errorlevel 1 exit 1
        set PATH=%CD%\build\bin;%CD%\build\lib;%CD%\build\Release;%CD%\build\bin\Release;%CD%\build\lib\Release;%PATH%
        if errorlevel 1 exit 1
        @REM Run tests, excluding the HTTP test which brings about a SEGFAULT error
        ctest -V -C Release --test-dir build -E "http-test"
        if errorlevel 1 exit 1
        cmake --install build
        if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then: make
    - pkg-config
  host:
    - asio
    - catch2
    - howardhinnant_date
    - nlohmann_json
    - zeem
    - if: linux
      then: maartens_resource_compiler
  run_exports:
    - ${{ pin_subpackage("libzeep", upper_bound="x") }}
  ignore_run_exports:
    by_name:
      - catch2

tests:
  - package_contents:
      include:
        - zeep/*
      lib:
        - zeep
    strict: true

about:
  homepage: https://mhekkel.github.io/libzeep
  repository: https://forge.hekkelman.net/maarten/zeep
  documentation: https://mhekkel.github.io/libzeep
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: "C++ library for reading and writing XML and creating web, REST and SOAP servers"
  description: |
    Libzeep is a web application framework written in C++.
    To see a starter project visit the [libzeep-webapp-starter](https://github.com/mhekkel/libzeep-webapp-starter.git) page.

extra:
  recipe-maintainers:
    - eunos-1128
